import sys
import time
import signal
import threading
import traceback
import subprocess

import requests


# ============================================================
# THESE VALUES ARE GENERATED BY GITHUB ACTIONS.
# DO NOT ADD ${...} HERE.
# DO NOT READ THEM FROM ENVIRONMENT.
# ============================================================

SESSION_ID = "__SESSION_ID__"
API_URL = "__API_URL__"
WORKER_TOKEN = "__WORKER_TOKEN__"


# ============================================================
# CONFIG
# ============================================================

HEARTBEAT_INTERVAL = 10
STATUS_INTERVAL = 10
COMMAND_INTERVAL = 3

REQUEST_TIMEOUT = 15

# Real GPU workload.
# 16 million float32 elements ≈ 64 MB per array.
N = 16 * 1024 * 1024

STOP_EVENT = threading.Event()


# ============================================================
# LOG
# ============================================================

def log(message=""):
    print(message, flush=True)


def section(title):
    log()
    log("=" * 60)
    log(title)
    log("=" * 60)


# ============================================================
# VALIDATION
# ============================================================

def validate_config():

    if not SESSION_ID:
        raise RuntimeError(
            "SESSION_ID is empty"
        )

    if SESSION_ID.startswith("__"):
        raise RuntimeError(
            "SESSION_ID was not injected"
        )

    if "${" in SESSION_ID:
        raise RuntimeError(
            "SESSION_ID still contains shell placeholder"
        )

    if not API_URL:
        raise RuntimeError(
            "API_URL is empty"
        )

    if API_URL.startswith("__"):
        raise RuntimeError(
            "API_URL was not injected"
        )

    if "${" in API_URL:
        raise RuntimeError(
            "API_URL still contains shell placeholder"
        )

    if not WORKER_TOKEN:
        raise RuntimeError(
            "WORKER_TOKEN is empty"
        )

    if WORKER_TOKEN.startswith("__"):
        raise RuntimeError(
            "WORKER_TOKEN was not injected"
        )

    if "${" in WORKER_TOKEN:
        raise RuntimeError(
            "WORKER_TOKEN still contains shell placeholder"
        )

    if not API_URL.startswith(
        ("http://", "https://")
    ):
        raise RuntimeError(
            f"Invalid API_URL: {API_URL}"
        )


# ============================================================
# AUTH
# ============================================================

def headers():

    return {
        "Authorization": f"Bearer {WORKER_TOKEN}",
        "X-Worker-Token": WORKER_TOKEN,
        "Content-Type": "application/json",
        "User-Agent": "kaggle-gpu-worker/1.0",
    }


# ============================================================
# API GET
# ============================================================

def api_get(path):

    url = API_URL + path

    try:

        response = requests.get(
            url,
            headers=headers(),
            timeout=REQUEST_TIMEOUT,
        )

        log(
            f"[API] GET {path} -> "
            f"{response.status_code}"
        )

        return response

    except Exception as exc:

        log(
            f"[API] GET ERROR {path}: {exc}"
        )

        return None


# ============================================================
# API POST
# ============================================================

def api_post(
    path,
    payload=None,
):

    url = API_URL + path

    try:

        response = requests.post(
            url,
            headers=headers(),
            json=payload or {},
            timeout=REQUEST_TIMEOUT,
        )

        log(
            f"[API] POST {path} -> "
            f"{response.status_code}"
        )

        if response.status_code >= 400:
            log(
                response.text[:1000]
            )

        return response

    except Exception as exc:

        log(
            f"[API] POST ERROR {path}: "
            f"{exc}"
        )

        return None


# ============================================================
# NVIDIA
# ============================================================

def show_nvidia_smi():

    section("NVIDIA-SMI")

    process = subprocess.run(
        ["nvidia-smi"],
        capture_output=True,
        text=True,
        timeout=30,
    )

    log(process.stdout)

    if process.stderr:
        log(process.stderr)

    if process.returncode != 0:
        raise RuntimeError(
            "nvidia-smi failed"
        )


def gpu_details():

    process = subprocess.run(
        [
            "nvidia-smi",
            "--query-gpu="
            "name,memory.total,"
            "memory.used,memory.free,"
            "temperature.gpu,"
            "utilization.gpu,"
            "driver_version",
            "--format=csv,noheader",
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )

    if process.returncode != 0:
        return None

    return process.stdout.strip()


# ============================================================
# CUDA TEST
# ============================================================

def initialize_cuda():

    section("CUDA / NUMBA")

    import numpy as np
    from numba import cuda

    if not cuda.is_available():

        raise RuntimeError(
            "CUDA is unavailable"
        )

    device = cuda.get_current_device()

    capability = device.compute_capability

    log(
        f"CUDA available: True"
    )

    log(
        f"GPU: {device.name}"
    )

    log(
        f"Compute capability: {capability}"
    )


    @cuda.jit
    def test_kernel(a, b, c):

        i = cuda.grid(1)

        if i < c.size:
            c[i] = a[i] + b[i]


    n = 1024 * 1024

    a = np.ones(
        n,
        dtype=np.float32,
    )

    b = np.ones(
        n,
        dtype=np.float32,
    )

    c = np.empty_like(a)

    da = cuda.to_device(a)
    db = cuda.to_device(b)
    dc = cuda.device_array_like(c)

    threads = 256

    blocks = (
        n + threads - 1
    ) // threads


    started = time.perf_counter()

    test_kernel[
        blocks,
        threads
    ](
        da,
        db,
        dc,
    )

    cuda.synchronize()

    elapsed = (
        time.perf_counter()
        - started
    )

    result = dc.copy_to_host()

    if not np.allclose(
        result,
        2.0,
    ):
        raise RuntimeError(
            "CUDA verification failed"
        )

    log(
        f"CUDA test OK: "
        f"{n} elements "
        f"in {elapsed:.4f}s"
    )

    return (
        cuda,
        capability,
    )


# ============================================================
# WORKER READY
# ============================================================

def notify_ready(
    gpu,
    capability,
):

    section("NOTIFYING RAILWAY")

    payload = {
        "gpu": gpu_details(),
        "cuda_available": True,
        "compute_capability": [
            int(capability[0]),
            int(capability[1]),
        ],
    }

    path = (
        f"/gpu/session/"
        f"{SESSION_ID}/worker-ready"
    )

    for attempt in range(1, 11):

        log(
            f"worker-ready "
            f"attempt {attempt}/10"
        )

        response = api_post(
            path,
            payload,
        )

        if (
            response is not None
            and response.status_code == 200
        ):

            log(
                "WORKER READY accepted by Railway."
            )

            return True

        time.sleep(3)

    return False


# ============================================================
# HEARTBEAT
# ============================================================

def heartbeat_loop():

    counter = 0

    while not STOP_EVENT.is_set():

        counter += 1

        response = api_post(
            f"/gpu/session/"
            f"{SESSION_ID}/heartbeat",
            {
                "worker_alive": True,
                "timestamp": time.time(),
            },
        )

        if response is not None:

            if response.status_code == 200:

                log(
                    f"[HEARTBEAT] #{counter} OK"
                )

            elif response.status_code == 410:

                log(
                    "Session expired."
                )

                STOP_EVENT.set()
                return

            elif response.status_code == 401:

                log(
                    "Heartbeat unauthorized."
                )

        STOP_EVENT.wait(
            HEARTBEAT_INTERVAL
        )


# ============================================================
# SESSION MONITOR
# ============================================================

def session_monitor_loop():

    while not STOP_EVENT.is_set():

        response = api_get(
            f"/gpu/session/"
            f"{SESSION_ID}"
        )

        if response is not None:

            try:

                data = response.json()

                status = data.get(
                    "status"
                )

                remaining = data.get(
                    "remaining_seconds"
                )

                log(
                    f"[SESSION] "
                    f"status={status} "
                    f"remaining={remaining}"
                )

                if status in (
                    "expired",
                    "stopped",
                    "error",
                ):

                    log(
                        "Session ended."
                    )

                    STOP_EVENT.set()
                    return

            except Exception:
                pass

        STOP_EVENT.wait(
            STATUS_INTERVAL
        )


# ============================================================
# COMMAND MONITOR
# ============================================================

def command_loop():

    while not STOP_EVENT.is_set():

        response = api_get(
            f"/internal/session/"
            f"{SESSION_ID}/command"
        )

        if response is not None:

            if response.status_code == 200:

                try:

                    data = response.json()

                    if data.get("expired"):

                        STOP_EVENT.set()
                        return

                    command = data.get(
                        "command"
                    )

                    if command:

                        log(
                            "[COMMAND] received:"
                        )

                        log(
                            str(command)
                        )

                        # We currently reserve the normal
                        # continuous GPU worker for the Job.
                        #
                        # stop command can safely stop it.

                        if (
                            isinstance(
                                command,
                                dict
                            )
                            and command.get(
                                "operation"
                            ) == "stop"
                        ):

                            STOP_EVENT.set()
                            return

                except Exception as exc:

                    log(
                        f"[COMMAND] parse error: {exc}"
                    )

        STOP_EVENT.wait(
            COMMAND_INTERVAL
        )


# ============================================================
# REAL GPU WORKLOAD
# ============================================================

def gpu_job(
    cuda,
):

    section("REAL CONTINUOUS GPU JOB")

    import numpy as np

    log(
        f"GPU workload size: "
        f"{N:,} float32 elements"
    )

    log(
        "Allocating GPU memory..."
    )


    # --------------------------------------------------------
    # Allocate roughly 192 MB total.
    # --------------------------------------------------------

    a = np.ones(
        N,
        dtype=np.float32,
    )

    b = np.ones(
        N,
        dtype=np.float32,
    )

    da = cuda.to_device(a)
    db = cuda.to_device(b)

    dc = cuda.device_array(
        N,
        dtype=np.float32,
    )


    @cuda.jit
    def workload(a, b, c):

        i = cuda.grid(1)

        if i < c.size:

            x = a[i]
            y = b[i]

            # Real arithmetic workload.
            for _ in range(32):

                x = (
                    x * 1.000001
                    + y * 0.999999
                )

            c[i] = x


    threads = 256

    blocks = (
        N + threads - 1
    ) // threads


    # --------------------------------------------------------
    # Warmup
    # --------------------------------------------------------

    log(
        "Compiling GPU workload..."
    )

    workload[
        blocks,
        threads
    ](
        da,
        db,
        dc,
    )

    cuda.synchronize()

    log(
        "GPU workload compiled."
    )


    # --------------------------------------------------------
    # Continuous job
    # --------------------------------------------------------

    iteration = 0

    started = time.monotonic()

    last_report = started


    while not STOP_EVENT.is_set():

        workload[
            blocks,
            threads
        ](
            da,
            db,
            dc,
        )

        cuda.synchronize()

        iteration += 1


        now = time.monotonic()


        if (
            now - last_report
            >= 5
        ):

            elapsed = (
                now - started
            )

            details = gpu_details()

            log(
                f"[GPU JOB] "
                f"iterations={iteration} "
                f"elapsed={elapsed:.1f}s"
            )

            if details:
                log(
                    f"[GPU STATUS] {details}"
                )

            last_report = now


    log(
        "GPU job stopping..."
    )


# ============================================================
# SIGNALS
# ============================================================

def handle_signal(
    signum,
    frame,
):

    log(
        f"Received signal {signum}"
    )

    STOP_EVENT.set()


signal.signal(
    signal.SIGTERM,
    handle_signal,
)

signal.signal(
    signal.SIGINT,
    handle_signal,
)


# ============================================================
# MAIN
# ============================================================

def main():

    section("KAGGLE GPU WORKER")

    validate_config()

    log(
        f"SESSION : {SESSION_ID}"
    )

    log(
        f"API     : {API_URL}"
    )

    # Never expose token itself.
    log(
        f"TOKEN   : {len(WORKER_TOKEN)} chars"
    )


    # --------------------------------------------------------
    # GPU
    # --------------------------------------------------------

    show_nvidia_smi()


    # --------------------------------------------------------
    # CUDA
    # --------------------------------------------------------

    cuda, capability = initialize_cuda()


    # --------------------------------------------------------
    # READY
    # --------------------------------------------------------

    if not notify_ready(
        cuda,
        capability,
    ):

        raise RuntimeError(
            "Could not notify Railway"
        )


    # --------------------------------------------------------
    # Background control threads
    # --------------------------------------------------------

    heartbeat_thread = threading.Thread(
        target=heartbeat_loop,
        daemon=True,
    )

    status_thread = threading.Thread(
        target=session_monitor_loop,
        daemon=True,
    )

    command_thread = threading.Thread(
        target=command_loop,
        daemon=True,
    )


    heartbeat_thread.start()
    status_thread.start()
    command_thread.start()


    # --------------------------------------------------------
    # REAL GPU JOB
    # --------------------------------------------------------

    gpu_job(cuda)


    section("WORKER FINISHED")

    log(
        "GPU worker exited normally."
    )


if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        log(
            "Worker interrupted."
        )

    except Exception as exc:

        section("WORKER ERROR")

        log(
            str(exc)
        )

        traceback.print_exc()

        sys.exit(1)
